### ISSUE TITLE
Subscriptions in .NET Framework

### ISSUE THREAD

**Issue by dillanmann** [graphql-dotnet/server#313] opened 2020-02-12 21:54 UTC
Are there any examples or efforts available to enable subscriptions on .NET Framework? All of the GraphQL middleware for WebSockets and subscriptions is written with ASPNET Core in mind and is not transferrable to .NET Framework. This unfortunately means that it looks like it's not possible to use subscriptions with GraphQL.net in NFX.

Pekkah provides some information on this in #167 RE the implementation of `IMessageTransport` but it seems like there is way more overhead to this.  

I'm really just looking to see if there is a suitable jumping off point to get stuck into it, so any existing attempts or research would be much appreciated.

Relevant information

Environment (if relevant)
FYI I am using OWIN Self-Host on .NET Framework 4.7.2

**Comment by pekkah** [comment] 2020-02-13 06:26
What's the reason you cannot use dotnet core?

**Comment by sungam3r** [comment] 2020-02-13 06:32
I can give my example. One of our services uses an ancient component for external system integration that was written many years ago and works only for .NET Framework. We are also forced to deploy service on a Windows machine.

**Comment by pekkah** [comment] 2020-02-13 06:41
Why not just add a graphql service to front of the older component? That way you can also start migrating things you can to core.

**Comment by sungam3r** [comment] 2020-02-13 06:48
We considered this option. This **can be** done, another thing is that there will be nothing more in the service, since all its work is reduced to calling that component methods. We will be forced to write a proxy service and do another hop on the network. We did not do this and placed the graphql api together with the component in the same process (something like hosting graphql executor in WebApi example). We do not use subscriptions, so the problem is not critical for us.

**Comment by pekkah** [comment] 2020-02-13 06:55
With grpc the hop shouldn't be that expensive. It adds complexity but you probably already have enough abstractions to make it work if you're doing integration with an ancient system.

Support for non-core is not trivial to add but doable but I would recommend no one adds it to this repo unless you want to be constantly implementing things for two different frameworks. This would get even more complicated when .NET 5 comes.

**Comment by sungam3r** [comment] 2020-02-13 07:04
I understand that any problem can be solved by introducing an additional level of indirection. But we do not help @dillanmann  much with this.

**Comment by dillanmann** [comment] 2020-02-13 08:33
> 
> 
> What's the reason you cannot use dotnet core?

It's as you say, an old application that we are adding GraphQL access to. At the moment .NET Core is a possibility but it adds a whole lot of overhead that we could otherwise avoid if we keep using NFX. My preference is NET Core but as with all things it doesn't necessarily matter what my preference is 😄 



> 
> 
> I can give my example. One of our services uses an ancient component for external system integration that was written many years ago and works only for .NET Framework. We are also forced to deploy service on a Windows machine.

I would really appreciate if you could share that with me. I agree with Pekkah that this should't become part of the server repo due to the maintenance issues, but I am happy to maintain it elsewhere if it works.

At this point queries and mutations work completely fine in our NFX solution with subscriptions being the only blocker. 


> 
> 
> Why not just add a graphql service to front of the older component? That way you can also start migrating things you can to core.

Could you provide some more detail on what you mean by this? I am happy to explore any potential options that you think are feasible.

**Comment by sungam3r** [comment] 2020-02-13 11:57
> I would really appreciate if you could share that with me.

I'm afraid I do not understand. Share what exactly?

**Comment by dillanmann** [comment] 2020-02-13 12:01
> 
> 
> > I would really appreciate if you could share that with me.
> 
> I'm afraid I do not understand. Share what exactly?

Ah sorry that's just my misunderstanding - I thought when you said 'I can give my example' you had code to share not just the situation.

**Comment by sungam3r** [comment] 2020-02-13 14:03
OK

**Comment by sungam3r** [comment] 2020-07-24 21:13
I generally agree with @pekkah so closing.

**Closed by sungam3r** 2020-07-24 21:13 UTC
Labels: question, subscriptions, wontfix
