### ISSUE TITLE
Support for ASP.NET Core 3.0 ?

### ISSUE THREAD

**Issue by EdgarMaucourant** [graphql-dotnet/server#276] opened 2019-10-15 14:33 UTC
Hi Guys,

Is there a plan to support  Dotnet core 3.0 ?
As Microsoft is terminating the support of .net core 2.2 in December we are a bit in a hurry to migrate our applications to .netcore 3.0.

Best regards
Edgar

**Comment by sungam3r** [comment] 2019-10-15 17:10
I am sure that this is inevitable. The migration process should not be difficult. Maybe a little later. Most likely, another target will appear in the package, there will be no separate package.

**Comment by benmccallum** [comment] 2019-10-18 10:01
I'm trying to update, but the issue I'm currently having is that `AddAuthorization` has been renamed to `AddAuthorizationCore`, so the call in the `AddGraphQLAuthorization` is failing on method not found. 

https://github.com/aspnet/Announcements/issues/386

**Comment by benmccallum** [comment] 2019-10-18 10:07
I might be able to give the multi-targeting issue a go today, since it's blocking me.

**Comment by EdgarMaucourant** [comment] 2019-10-18 10:26
Hi benmccallum,

I also did try, and fixed the AddAuthorizationCore (by editing the source directly), but then I run also on conflict in the GraphQL code, so I gave up for the moment, and will try later. I let you know if I manage to get this working, but as I'm on tight deadline for the project, it will be not before 10 of November in think.

Edgar

**Comment by benmccallum** [comment] 2019-10-18 12:15
Do you have a branch you could push for this repo?

You had an issue with the main GraphQL package too? Hmm... what I'm unsure about is whether we can keep Microsoft.Extensions.Xyz 2.x versions, or they need to be upgraded to 3.0.0, which probably requires netcoreapp3.0, and then it's a big issue.

**Comment by sungam3r** [comment] 2019-10-18 12:20
Multitargeting with Conditional csproj switches all the way...

**Comment by benmccallum** [comment] 2019-10-18 12:22
And by all the way you mean in this repo and graphql? Hmm, I can give it a go I suppose :)

**Comment by benmccallum** [comment] 2019-10-18 12:23
I think the biggest pain point is that some of upgraded to 2.2 but its only 2.1 that is LTS, so we're like... up sh*t creek unless we wanna back down to 2.1 which is just nasty.

**Comment by benmccallum** [comment] 2019-10-18 12:44
@sungam3r , I'm going to create a branch for this project support 3.0.0, should I do it off develop or master?

**Comment by sungam3r** [comment] 2019-10-18 13:32
> And by all the way you mean in this repo and graphql? Hmm, I can give it a go I suppose :)

netstandard2.0 and netstandard2.1 in graphql-dotnet

**Comment by sungam3r** [comment] 2019-10-18 13:41
Sorry, I did not immediately realize that the original question was posed incorrectly. In fact, all packages are targeted at `netstandard2.0` now. So it's all not about targeting `netcoreapp3.0` but about targeting `netstandard2.1`. 

> I think the biggest pain point is that some of upgraded to 2.2 but its only 2.1 that is LTS, so we're like... up sh*t creek unless we wanna back down to 2.1 which is just nasty.

No, these problems do not exist, since the code does not use a specific platform.

**Comment by sungam3r** [comment] 2019-10-18 13:44
Moreover, since `netstandard2.1` has no changed api, then for `netcoreapp3.0` you **can** just use the current version of the library which targets `netstandard2.0`.

**Comment by sungam3r** [comment] 2019-10-18 13:52
@EdgarMaucourant @benmccallum I changed the issue title to fit the essence of the problem.

**Comment by benmccallum** [comment] 2019-10-18 13:52
I wish it was that simple. I think the problem is that if you rely on any of the packages listed here that are now consolidated in to the shared netcore3 framework, you need `<FrameworkReference Include="Microsoft.AspNetCore.App" />`, which is only supported if you target `netcoreapp3.0`.  `https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#remove-obsolete-package-references

So for us:
1. Authorization.AspNetCore - references `Microsoft.AspNetCore.Authorization` and `...Http`
1. Transports.AspNetCore - references `Microsoft.AspNetCore.Hosting.Abstractions`
1. Core - references Microsoft.Extensions.Xyz packages at v2.2 - this is one thing I'm not sure about, will they "just work" if the runtime is executing as `netcoreapp3.0`?
1. Transports.Subscriptions.Abstractions - same as Core above
1. Transports.Subscriptions.WebSockers - references `Microsoft.AspNetCore.WebSockets`. 

So in my mind 1, 2 and 5 need multi-targeting to `netcoreapp3.0`, conditionally including `<FrameworkReference Include="Microsoft.AspNetCore.App" />` and, since we can, pointing definitively at 3.0.0 `Microsoft.Extensions.Xyz` packages.

For 3 and 4 though, I'm not sure.

**Comment by sungam3r** [comment] 2019-10-18 14:18
Well, you just need to start this path. And then we will see how the dependencies are laid out. Essentially, we have a current workable dependency configuration. We are adding a second.

If in some place you need to change part of the api of one of the server packages to embed it smoothly in ASP.NET Core 3.0, then this can be done using preprocessor directives. This is standard practice as an alternative to completely copying code to separate files like GraphQLMiddleware2.0.cs and GraphQLMiddleware3.0.cs.

**Comment by benmccallum** [comment] 2019-10-18 14:21
Yep, almost there, just checking everything builds and will try running it up soon. Fingers crossed I've got it right. In any case, it seems like netstandard is dead moving fwd as netcoreapp5.0 will just be everything I guess *shrugs*. basically I'm saying even though it feels weird adding this to some libraries, it'd be the default moving forward.

**Comment by sungam3r** [comment] 2019-10-18 15:31
> it seems like netstandard is dead 

Why? It is just a set of common apis. ASP.NET Core is not a set of apis, it is a framework. If some `netstandard2.0` package does not fit with the new version of ASP.NET Core framework, then we cannot say that this is a package problem. ASP.NET Core changes the rules of the game, not netstandard. And we... we adapt to them all sooner or later :).

**Comment by benmccallum** [comment] 2019-10-18 17:16
Because `netstandard2.1` isn't supported by full .net framework and .net 5 is just .net core, which is cross-plat, so the need for .net standard goes away. I'm probably being very limited in view here though, as I guess there's other runtimes that could find it useful. 

https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by sungam3r** [comment] 2019-10-18 19:04
> so the need for .net standard goes away

[Really?](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)
![изображение](https://user-images.githubusercontent.com/21261007/67121020-30d31e80-f1f3-11e9-8273-237c1c8c20db.png)

**Comment by pkellner** [comment] 2019-11-12 17:25
If I want to do some non-production work and use the asp.net core 3.0, what's the best plan? That is, what sample project should I use that lets me create a graphql server from entity framework data.  I see there is a "develop" branch on the server project but it's not obvious if I should us that sample, or one from this repo (graphql-dotnet) but there is no "develop" branch here.

**Comment by sungam3r** [comment] 2019-11-12 22:38
Default branch in that repo (develop) has a fully functional graphql ASP.NET Core 3.0 [server](https://github.com/graphql-dotnet/server/tree/develop/samples/Samples.Server). You can modify it while studying ASP.NET Core 3.0.

**Comment by yass98** [comment] 2019-12-03 13:42
Hello,
When new nuget-package with fixed problem of authorization will be available?
> AddAuthorization has been renamed to AddAuthorizationCore, so the call in the AddGraphQLAuthorization is failing on method not found.

**Comment by sungam3r** [comment] 2019-12-03 17:32
The package was already ready -  https://github.com/graphql-dotnet/server/blob/develop/nuget.config

**Comment by sungam3r** [comment] 2019-12-03 17:33
@benmccallum maybe it's time to close this issue?

**Comment by benmccallum** [comment] 2019-12-03 20:45
Yea that method rename issue was definitely addressed in my PR and is now in develop and being released in the alpha packages, @sungam3r. Feel free to close and direct them to a version and feed that's got it in there.

**Comment by sungam3r** [comment] 2019-12-03 21:46
@yass98 You can use the latest preview version from aforementioned myget feed.

**Closed by sungam3r** 2019-12-03 21:46 UTC
Labels: discussion, enhancement
