### ISSUE TITLE
SignalR (Core) transport

### ISSUE THREAD

**Issue by pekkah** [graphql-dotnet/server#55] opened 2018-01-16 19:54 UTC
It would be nice to have an Apollo Link for client side using the new SignalR and have a transport compatible with that client.

**Comment by BenjaBobs** [comment] 2018-03-22 08:04
Will this also allow for WSS (WebSocket Secure) protocol?

**Comment by pekkah** [comment] 2018-03-22 08:20
Plan was to let SignalR take care of the transport so whatever it supports would be supported. 
This requires creating a custom Apollo Link + a custom backend transport on top of SignalR "hub".

Have been waiting for Core 2.1 with SignalR Core release to make any real progress with this.

**Comment by pekkah** [comment] 2018-03-22 08:24
Hmm is there some issue with WSS?

**Comment by BenjaBobs** [comment] 2018-03-22 08:36
I'm not sure, but I couldn't get it to work. I'm about to update packages and will report back when I have tested further.

**Comment by pekkah** [comment] 2018-03-22 08:41
Could you create a separate issue about it?

**Comment by RehanSaeed** [comment] 2018-04-12 15:40
Doesn't graphql-dotnet already support subscriptions which I assume are using web sockets directly. What benefit would Signal-R provide?

**Comment by maldworth** [comment] 2019-03-10 02:55
@pekkah you mentioned custom Apollo Link would need to be made, does that mean one would have to create a PR into https://github.com/apollographql/apollo-link/tree/master/packages for an `apollo-link-signalr` ?
and also a `subscriptions-transport-signalr`? I'm just trying to gauge what pieces need to be done.

**Comment by pekkah** [comment] 2019-03-10 04:47
This is what is needed https://github.com/pekkah/tanka-graphql/tree/master/src/graphql.server.link

**Comment by maldworth** [comment] 2019-03-12 01:25
this is great, thanks!

**Comment by BenjaBobs** [comment] 2019-03-12 07:54
I would like to bump @RehanSaeed's question. I'm not very familiar with SignalR, what is the benefit of that over the current websocket solution?

**Comment by pekkah** [comment] 2019-03-12 12:15
If you compare the amount of code in https://github.com/pekkah/tanka-graphql/tree/master/src/graphql.server vs what's included in this server you should notice that it's simpler. Also signalr provides other transports besides websockets for example server events. Also it integrates with the rest of the asp.net core infrastructure in a more flexible way.

**Comment by maldworth** [comment] 2019-03-13 15:36
another benefit was somebody had asked about scaleout with a backplane for websockets. SignalR has backplane capabilities. So I think that can apply to a graphApi subscriptions with SignalR backplane option enabled.

**Comment by sgwozdz** [comment] 2019-07-15 12:13
Wondering what's the status of SignalR support. Is it considered as feature for next releases ?

**Comment by joemcbride** [comment] 2019-07-15 15:41
@sgwozdz No one is currently working on this feature for this project, as far as I'm aware.

**Comment by Shane32** [comment] 2022-07-19 16:58
Duplicate of #289

**Closed by Shane32** 2022-07-19 16:58 UTC
Labels: enhancement
