### ISSUE TITLE
NFR(graphiql): provide a way to disable websockets in graphiql

### ISSUE THREAD

**Issue by cyberhck** [graphql-dotnet/server#511] opened 2021-02-28 19:25 UTC
currently for some reason it throws an exception while trying to upgrade a GET request to websocket connection inside a graphql middleware, also for me I don't have a need for websockets in my projects, I'd like to be able to disable websockets entirely :)

This is a 2 part issue though, maybe the graphql middleware should also make sure the upgrade GET request is handled correctly,

and a way for us to disable websockets in playground

**Comment by dasco144** [comment] 2021-03-08 14:34
Is it this exception? 

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Cannot execute request if no query is specified
         at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 56
         at GraphQL.Server.Internal.DefaultGraphQLExecuter`1.ExecuteAsync(String operationName, String query, Inputs variables, IDictionary`2 context, IServiceProvider requestServices, CancellationToken cancellationToken) in /_/src/Core/Internal/DefaultGraphQLExecuter.cs:line 54
         at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 144
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

If so I'm getting the same thing whenever I have GraphiQL open. Not sure if the issue is the server or GraphiQL itself though

**Comment by cyberhck** [comment] 2021-03-08 16:57
yes, that's exactly the exception

**Comment by hero3616** [comment] 2021-10-30 17:45
I'm having the same issue with graphql-dotnet app.UseGraphQLPlayground() works fine but app.UseGraphQLGraphiQL() throws the exception above. Any suggestion?

**Comment by Shane32** [comment] 2021-10-30 21:48
Possibly solved already by:
- #584 

That specific bug fix isn’t in the latest release

**Comment by Shane32** [comment] 2022-07-12 19:50
Closing as solved; please re-open if there is continuing issues with this.

**Closed by Shane32** 2022-07-12 19:50 UTC
