### ISSUE TITLE
 graphql-dotnet/server always consuming memory for IntrospectionQuery

### ISSUE THREAD

**Issue by hasibul2363** [graphql-dotnet/server#182] opened 2018-12-04 12:48 UTC
I am using **graphql-dotnet/server** to host my services. I have made my schema class singleton. For every  IntrospectionQuery it is increasing the memory consumption by the server. So more more and request comes in memory goes high.  Is there any solution to minimize this issue. 
Expecting your help. I am using the following code to initialize my graphQL service and my schema class is a singleton
```
services.AddGraphQL(_ =>
                {
                    _.EnableMetrics = true;
                    _.ExposeExceptions = true;
                });
services.AddSingleton<PdsGraphQlSchema>();
```
and inside Configure I have used following
```
app.UseGraphQL<PdsGraphQlSchema>();
app.UseGraphQLPlayground(new GraphQLPlaygroundOptions
{
	Path = "/ui/playground"
});
```
Expecting your help.

**Comment by hasibul2363** [comment] 2018-12-14 12:10
Still expecting your help and valuable suggestions.

**Comment by pekkah** [comment] 2018-12-18 16:01
Have you done any profiling to see what is increasing the memory consumption?

**Comment by igorvuleta** [comment] 2019-09-09 10:57
Can confirm that this is still active I switchted to graphiql today and the ammount of fre memory is around 1.5GB in my case where I really have a big API. Even when I turn of polling the app consumption is around 1GB, on graphiql meanwhile it's around 600ish MB.

**Comment by sungam3r** [comment] 2019-09-09 17:01
You can use any memory profiling tool, for example, [clrmd](https://github.com/microsoft/clrmd).

**Comment by sungam3r** [comment] 2020-03-01 00:00
@hasibul2363 @igorvuleta This memory issue probably was fixed in graphql-dotnet/graphql-dotnet#1339 . Try the latest preview versions and let me know if the problem is still here.

**Comment by chinwobble** [comment] 2020-03-08 10:01
I tried with `3.5.0-alpha0046`.
Ran the `ui/playground` for 20 mins continuously polling on my graph with 30+ custom types.

Memory stayed constant at 443 MB.

**Comment by sungam3r** [comment] 2020-03-20 20:01
Closing this as solved.

**Closed by sungam3r** 2020-03-20 20:01 UTC
Labels: question
