### ISSUE TITLE
Cannot use scoped schema

### ISSUE THREAD

**Issue by fubar-coder** [graphql-dotnet/server#124] opened 2018-06-19 14:40 UTC
I cannot use a schema registered as scoped, because `GraphQLHttpMiddleware` requires a `TSchema` instance in its constructor. Instead, it should request a `TSchema` instance from the `HttpContext.RequestServices`. This allows using a `TSchema` that is either registered as scoped or as singleton.

**Comment by johnrutherford** [comment] 2018-06-19 15:36
This is an duplicate of issue #107. I'm working on a pull request to address this.

**Closed by johnrutherford** 2018-06-19 15:36 UTC
