### ISSUE TITLE
FileLoadException 'Could not load file or assembly 'GraphQL, Version=3.0.0.1490, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference.

### ISSUE THREAD

**Issue by markmcgookin** [graphql-dotnet/server#374] opened 2020-07-20 13:09 UTC
I have the following references in my project 

```
<PackageReference Include="GraphQL" Version="3.0.0-preview-1648" />
<PackageReference Include="GraphQL.SystemTextJson" Version="3.0.0-preview-1648" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0046" />
<PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="3.5.0-alpha0046" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="3.5.0-alpha0046" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.5.0-alpha0046" />
```

My startup looks like this:

```
services.AddSingleton<ISchema, CoreSchema>();

services.AddGraphQL(o => { o.ExposeExceptions = Environment.IsDevelopment(); })
    .AddSystemTextJson()
    .AddGraphTypes(ServiceLifetime.Scoped)
    .AddDataLoader()
    .AddWebSockets();

services.AddSingleton<IDocumentExecuter, DocumentExecuter>();
```

I am getting the following runtime exception:

```
Exception has occurred: CLR/System.IO.FileLoadException
An unhandled exception of type 'System.IO.FileLoadException' occurred in GraphQL.Server.Core.dll: 'Could not load file or assembly 'GraphQL, Version=3.0.0.1490, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)'
   at GraphQL.Server.ServiceCollectionExtensions.AddGraphQL(IServiceCollection services, Func`2 options)
   at GraphQL.Server.ServiceCollectionExtensions.AddGraphQL(IServiceCollection services, Action`2 configureOptions)
   at GraphQL.Server.ServiceCollectionExtensions.AddGraphQL(IServiceCollection services, Action`1 configureOptions)
   at <mynamespace>.ConfigureServices(IServiceCollection services) in /Users/<myproject>/API/Startup.cs:line 321
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
```

According to nuget all dependencies are looking for **>=** 3.0.0.1490 but this looks like there's an explicit reference to 1490 somewhere. 

EDIT - Just seen another person seems to have mentioned this in #370 but they have closed that issue. I'll leave this open until there is a confirmed fix to the reference.

**Comment by sungam3r** [comment] 2020-07-20 17:02
Could you please post a repro project?

**Comment by paziz001** [comment] 2020-07-21 07:51
I am having the same issue with the same setup

**Comment by markmcgookin** [comment] 2020-07-21 08:11
Interestingly I just created a bare webapi project with SUPER basic settings [here](https://github.com/markmcgookin/graphql-dependency-issue) and it seems to be working ok. I wonder if something was cached (I did clear locals when seeing the issue though) I wonder if this is some other library clashing behind the scenes? I won't know until I retry this on my main production project

**Comment by markmcgookin** [comment] 2020-07-21 08:13
Ok [THIS](https://github.com/markmcgookin/graphql-dependency-issue) repo shows the issue for me. I thought it had fixed itself, but I actually had the 1490 version referenced there. Now that I reference 1648 it's breaking and showing the issue

**Comment by sungam3r** [comment] 2020-07-22 22:40
Remove this `<PackageReference Include="GraphQL" Version="3.0.0-preview-1648" />` line and change `<PackageReference Include="GraphQL.SystemTextJson" Version="3.0.0-preview-1648" />` to `<PackageReference Include="GraphQL.SystemTextJson" Version="3.0.0-preview-1490" />`.

3.5.0-alpha0046 server packages depend on 1490 graphql "core". You explicitly reference higher version 1648 and project use it instead of 1490.

graphql-dotnet/graphql-dotnet#1612 should improve the versioning situation. I don't remember the details, but it looks like I ran into a similar situation myself - `The located assembly's manifest definition does not match the assembly reference`.

So you have 2 ways:
1. Rollback to 1490.
2. Upgrade to the latest 3.0.0-previews from myget feed. See readme for info.

I recommend you to upgrade.

**Comment by HrvojeFER** [comment] 2020-08-07 11:12
I can confirm that rolling back to 1490 fixes this. I don't know about the upgrade because my boss wouldn't be happy about adding myget as a feed in our projects.

**Comment by sungam3r** [comment] 2020-08-07 12:32
Closed as resolved.

**Closed by sungam3r** 2020-08-07 12:32 UTC
