### ISSUE TITLE
Plans for stable release?

### ISSUE THREAD

**Issue by msheldon83** [graphql-dotnet/server#268] opened 2019-10-02 19:34 UTC
I see that you are revving on an alpha release that implements some newer features for the apollo client (such as request batching).   Do you have a goal for a stable release at some point in the future?  

Thanks

**Comment by sungam3r** [comment] 2019-10-03 07:35
Relates to graphql-dotnet/graphql-dotnet#1321

I think the reason is the same - actual documentation.

**Comment by sungam3r** [comment] 2020-02-22 21:03
Closed as duplicate of graphql-dotnet/graphql-dotnet#1321

**Closed by sungam3r** 2020-02-22 21:03 UTC
Labels: duplicate, question
