### ISSUE TITLE
PubSub Implementations

### ISSUE THREAD

**Issue by narbit** [graphql-dotnet/server#223] opened 2019-05-08 23:16 UTC
Possible duplicate of  #[135](https://github.com/graphql-dotnet/server/issues/135). How would one go about plugging an external PubSub into graphql-dotnet Subscriptions? Apollo has [graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions#pubsub-implementations) that serves as a bridge to external PubSub systems. Is there something like that in graphql-dotnet?

**Comment by Shane32** [comment] 2022-03-14 19:32
Is there any specifications for GraphQL support over SignalR?

**Comment by Shane32** [comment] 2022-07-25 01:02
Closing due to lack of input/discussion and duplicate of #135 .

**Closed by Shane32** 2022-07-25 01:02 UTC
Labels: question, subscriptions
