### ISSUE TITLE
Nuget publish workflow 5.1.0 failed

### ISSUE THREAD

**Issue by sharppanda** [graphql-dotnet/server#657] opened 2021-11-24 10:24 UTC
The packages new version failed during upload to nuget.org
`error: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).`

https://github.com/graphql-dotnet/server/actions/runs/1496115587

**Comment by sungam3r** [comment] 2021-11-24 11:01
Duplicate of #655

**Closed by sungam3r** 2021-11-24 11:01 UTC
