### ISSUE TITLE
Asp.net core 6 request aborted after 5 second timeout

### ISSUE THREAD

**Issue by Stoom** [graphql-dotnet/server#757] opened 2022-03-25 18:31 UTC
### Problem
I was having a lot of issues with any GQL query or mutation that takes more than 5 seconds.  After digging for a few days I found an article on Microsoft's site talking about `request draining` and how it has a non-configurable 5 second timeout before it aborts the request.

### Supporting docs
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/request-draining?view=aspnetcore-6.0

**Comment by Stoom** [comment] 2022-03-25 18:46
### Logs
```log
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[0]
      Using development certificate: CN=localhost (Thumbprint: F50FBBBC0EB0369BE78ECAEC5DBA1D1F71838AAA)
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly DarkLumos
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly Microsoft.AspNetCore.Watch.BrowserRefresh
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\REDACTED\src
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
      Connection id "0HMGEHTETR5LI" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
      Connection id "0HMGEHTETR5LI" started.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Request starting HTTP/1.1 POST http://localhost:5000/graphql application/json 35
dbug: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[0]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Wildcard detected, all requests with hosts will be allowed.
trce: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[2]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      All hosts are allowed.
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      2 candidate(s) found for the request path '/graphql'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Endpoint 'GraphQL WebSockets' with route pattern 'graphql' is valid for the request path '/graphql'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Endpoint 'GraphQL' with route pattern 'graphql' is valid for the request path '/graphql'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Request matched endpoint 'GraphQL'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Executing endpoint 'GraphQL'
dbug: Microsoft.AspNetCore.Server.Kestrel[25]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Connection id "0HMGEHTETR5LI", Request id "0HMGEHTETR5LI:00000002": started reading request body.
dbug: Microsoft.AspNetCore.Server.Kestrel[26]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Connection id "0HMGEHTETR5LI", Request id "0HMGEHTETR5LI:00000002": done reading request body.
info: GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware[0]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      GraphQL execution successfully completed in 00:00:05.1990850
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Executed endpoint 'GraphQL'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      An unhandled exception has occurred while executing the request.
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 171
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[9]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Connection id "0HMGEHTETR5LI" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      => SpanId:afa14e712dc91295, TraceId:b3410f9211406a2ebd212d229d45293c, ParentId:0000000000000000 => ConnectionId:0HMGEHTETR5LI => RequestPath:/graphql RequestId:0HMGEHTETR5LI:00000002
      Request finished HTTP/1.1 POST http://localhost:5000/graphql application/json 35 - 500 - text/plain;+charset=utf-8 5377.6997ms
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[10]
      => ConnectionId:0HMGEHTETR5LI
      Connection id "0HMGEHTETR5LI" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[2]
      Connection id "0HMGEHTETR5LI" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HMGEHTETR5LI" sending FIN because: "The Socket transport's send loop completed gracefully."
```

**Comment by sungam3r** [comment] 2022-03-25 19:02
1. What do you expect from the maintainers of that repo? What do you suggest?
2. Your logs don't contain timestamps. What should we understand looking at them?

**Comment by Shane32** [comment] 2022-03-25 19:19
The document discusses request draining after a completed response in which the request body is not read by the application.  For this repo, this is generally not the case as all POST requests are read completely before the GraphQL request is processed.  But it could be simulated by sending a GraphQL request with an invalid content-type and a very large request body over a slow connection.  GraphQL would attempt to send a 'bad request' response prior to reading the content, and Kestrel would need to drain the content body.

Keep in mind, this is a 5-second timeout to complete reading the passed data from the client -- not a 5 second timeout to perform any processing of data.  I cannot see how this 5-second fixed timeout is bad or would affect any typical scenario to be concerned about.  If the timeout occurs, it can only be because the client sent some content which the server was not expecting (and so probably should not have been sent).

**Comment by Stoom** [comment] 2022-03-25 19:34
Is there another place that would have a 5 second timeout before aborting the request?  I'm having a hard time tracking down any such thing but can easily reproduce it with the following resolver on an asp.net core 6 project

```csharp
public Task<bool> Foobar() => Task.Delay(TimeSpan.FromMilliseconds(4995)).ContinueWith(_ => true);
```

**Comment by Shane32** [comment] 2022-03-25 20:01
I do not have an answer yet.  I do not believe I have experienced it in my own code, but it certainly is evident here.

@sungam3r This is reproducible with this simple change to `ChatQuery.cs` in `Samples.Schemas.Chat`:

```cs
            FieldAsync<StringGraphType>("test", resolve: async context =>
            {
                await Task.Delay(6000, context.CancellationToken);
                return "ok";
            });
```

**Comment by Shane32** [comment] 2022-03-25 20:20
The Samples.Server uses a custom cancellation token in GraphQLHttpMiddlewareWithLogs that times out after 5 seconds.

**Comment by Shane32** [comment] 2022-03-25 20:21
```cs
        protected override CancellationToken GetCancellationToken(HttpContext context)
        {
            // custom CancellationToken example
            var cts = CancellationTokenSource.CreateLinkedTokenSource(base.GetCancellationToken(context), new CancellationTokenSource(TimeSpan.FromSeconds(5)).Token);
            return cts.Token;
        }
```

**Comment by Stoom** [comment] 2022-03-29 17:33
I did try to map a minimal api post and that does not abort after 5 seconds. I'm having a really hard time understanding who's aborting the request...

**Comment by Stoom** [comment] 2022-03-29 17:38
Just figured it out... this is really dumb.  The documentation did not work so I copied the sample server middleware.  Line for line I copied the override for `GetCancellationToken`.

Potential solution is to NOT have the timeout in that sample. Maybe create another middleware with the timeout or just comment it out?

**Comment by sungam3r** [comment] 2022-03-29 18:51
@Stoom It is just a sample, nothing more. You may use it as is or with any changes you want.

**Comment by Stoom** [comment] 2022-03-29 19:37
@sungam3r I guess my point is the documentation does not work with the current stable version of the library, then when you look at the sample there is this random timeout, that if you're copy pasting, throws you for a huge loop. An example of the after execution is not provided, so what is the significance of providing an example of a timeout?

**Comment by sungam3r** [comment] 2022-03-29 20:39
`develop` is current working branch.

> when you look at the sample there is this random timeout... An example of the after execution is not provided

I don't understand. The sample shows how one can limit execution for concrete time interval (5 seconds in this example). `base.GetCancellationToken(context)` returns `HttpContext.RequestAborted` and here we link this token with one that goes into signaled state after 5 seconds. It's just a user defined timeout, that's it.

**Comment by Stoom** [comment] 2022-03-30 06:33
Yes, but it's something that can easily be missed when docs don't match and there are namespace conflicts.

**Comment by sungam3r** [comment] 2022-03-30 08:21
You may post a PR to warn users like you about such situation.

> // custom CancellationToken example

Modify that comment as you see fit.

**Comment by Shane32** [comment] 2022-03-31 05:41
@Stoom We have just released GraphQL 5.0.0 today and alongside it I have released a new server implementation under nuget package `GraphQL.AspNetCore3`.  With it you may write an entire working GraphQL server with .NET 6 with these few lines of code:

```cs
using GraphQL;
using GraphQL.AspNetCore3;
using GraphQL.MicrosoftDI;
using GraphQL.SystemTextJson;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddGraphQL(b => b
    .AddAutoSchema<Query>()  // schema
    .AddSystemTextJson());   // serializer

var app = builder.Build();
app.UseDeveloperExceptionPage();
app.UseWebSockets();
app.UseGraphQL("/graphql");  // url to host GraphQL endpoint
await app.RunAsync();

public class Query
{
    public static string Hero() => "Luke Skywalker";
}
```

If you want to use Playground, just add a nuget reference to `GraphQL.Server.UI.Playground` and this line before `await app.RunAsync();`:

```cs
app.UseGraphQLPlayground(
    new GraphQL.Server.Ui.Playground.PlaygroundOptions {
        GraphQLEndPoint = new PathString("/graphql"),
        SubscriptionsEndPoint = new PathString("/graphql"),
    },
    "/");
```

You can see a sample chat application at:
- https://github.com/Shane32/GraphQL.AspNetCore3/tree/master/src/Samples/BasicSample

And view the readme here which includes a copy of the csproj and a sample query and response:
- https://github.com/Shane32/GraphQL.AspNetCore3

Server v5.x is not compatible with GraphQL 5.x, and Server v6 has not yet been released.

**Comment by Stoom** [comment] 2022-03-31 16:31
@Shane32 ooh nice! is that package going to replace GraphQL.Server in the future?  It definingly fits in with the way aspnet core is going.

**Comment by sungam3r** [comment] 2022-03-31 16:35
There are no explicit purposes to replace this project. There are considerations of further evolution.

**Comment by Shane32** [comment] 2022-03-31 16:43
I designed the project to replace the middleware components of GraphQL.Server.  It is better in every respect, more documented, more tested, more bug fixes, better support for subscriptions.  There is no reason to continue to use the GraphQL.Server middleware.  I am hopeful that we may move all the new code back into the GraphQL.Server repository.  If others wish to maintain the old code, so be it.  I do plan to assist the transition of the code to the GraphQL.Server repo, if everyone is in agreement.

**Comment by Shane32** [comment] 2022-07-13 03:42
> @Shane32 ooh nice! is that package going to replace GraphQL.Server in the future? It definingly fits in with the way aspnet core is going.

Version 7 of GraphQL.NET Server has been almost entire replaced within the code in GraphQL.AspNetCore3, and will be released shortly.

Closing this issue as answered, as the original issue had to do with the provided sample demonstrating a 5-second timeout.

**Closed by Shane32** 2022-07-13 03:42 UTC
Labels: question
