### ISSUE TITLE
Extend schema-first authorization policy annotations to work on class properties

### ISSUE THREAD

**Issue by infogulch** [graphql-dotnet/server#505] opened 2021-02-17 20:00 UTC
Currently, `[GraphQLAuthorize(Policy = "...")]` can only be applied to methods and classes. I propose extending the `GraphQLAuthorizeAttribute` to allow one to apply it to class properties as well.

It turns out you can technically apply `GraphQLAuthorize` specifically to a getter or setter directly (as in `public int MyProperty { [GraphQLAuthorize(Policy="😲")] get; set; }`) , but that didn't magically work how I hoped it would.

I think this feature would be useful because sometimes the level that you want to populate/resolve data for a subquery is not perfectly aligned with the level you want to apply access authorization policies. For example, your backend queries the whole record, but some users should only have permission to access a subset of the fields¹. Yes, this strategy does not utilize 100% of the potential efficiency of graphql, but in some cases that optimization is not possible (e.g. a coarse rest backend), or desired (optimizing for implementation simplicity), etc.

¹ The nearest workaround that I've found is to wrap every record class in a second class that exposes the wrapped class' properties as methods with the same name that simply return the field from the contained record; adding the authorize attribute to those methods then allows one to define access policies. IMO this unnecessary duplication is clearly undesirable.

Thoughts?

**Comment by sungam3r** [comment] 2021-02-17 23:56
Both `GraphQLAuthorizeAttribute` from this project and https://github.com/graphql-dotnet/authorization inherit `GraphQLAttribute` from GraphQL.NET : 
```c#
 [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true)]
    public abstract class GraphQLAttribute : Attribute
    {
```

Moreover I can see code like ` public static PropertyInfo PropertyForField(this Type type, string field)` from GraphQL.NET that checks for this attribute applied to property. It looks like we just forgot to allow this attribute to be applied to properties and didn't notice it.

**Comment by infogulch** [comment] 2021-02-18 18:25
So does this mean that we should change `GraphQLAttribute` to allow properties like this:

```c#
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method | AttributeTargets.Property, AllowMultiple = true)]
    public abstract class GraphQLAttribute : Attribute
    {
```

Or should `GraphQLAuthorizeAttribute` in this repo be changed to specify these attribute targets?

**Comment by sungam3r** [comment] 2021-02-18 18:42
`GraphQLAttribute` should be changed.

**Comment by infogulch** [comment] 2021-02-18 19:34
[AuthorizationValidationRuleTests.cs#L285](https://github.com/graphql-dotnet/server/blob/master/tests/Authorization.AspNetCore.Tests/AuthorizationValidationRuleTests.cs#L285) validates method-attributed authorization policy.

Should we add additional tests in this repo to validate the new property authorization? For example, the class under test might look like:

```c#
        [GraphQLMetadata("Query")]
        public class BasicQueryWithAttributesAndPropertyPolicy
        {
            [GraphQLAuthorize(Policy = "FieldPolicy")]
            public string Post { get; set; } = "";
        }
```

**Comment by sungam3r** [comment] 2021-02-18 22:45
> Should we add additional tests

Of course.

> does that mean that this change would target GraphQL.NET release v4.0?

Yes. The release should be out soon. We've delayed it nearly three weeks from our initial plans. During this time, features and fixes have appeared that are critical for the normal operation of v4.

**Comment by sungam3r** [comment] 2021-02-19 17:30
https://github.com/graphql-dotnet/graphql-dotnet/pull/2298 was merged

**Comment by infogulch** [comment] 2021-03-31 20:14
Hi! I was excited to test the new releases to validate this enhancement, but I'm still running into some trouble. I can now apply the `[GraphQLAuthorize(policy)]`  to class properties 🎉!  But if the resolver returns an object with this attribute applied to one of its properties, it does not trigger an authorization check 😿. Thoughts?

**Comment by sungam3r** [comment] 2021-03-31 22:31
Could you provide a repro?

**Comment by infogulch** [comment] 2021-04-01 16:36
I created a PR which adds tests that reproduce/demonstrate the issue: #542 

Note in particular the [nested_property_policy_fail test](https://github.com/graphql-dotnet/server/pull/542/files#diff-d0bd98ceec4b5cc44006e96343f3612a39fab2f1ee046a9bc62d5cde8741f37eR179) which fails. See also [the schema](https://github.com/graphql-dotnet/server/pull/542/files#diff-d0bd98ceec4b5cc44006e96343f3612a39fab2f1ee046a9bc62d5cde8741f37eR370) where the object returned by the resolver has an authorize attribute applied to its property; this "nested"/"recursive" authorization strategy is the one I meant to describe above.

Does this make more sense?

**Comment by sungam3r** [comment] 2021-04-02 00:02
Thank you, I reproduced bug on your branch. Tomorrow I will try to answer.

**Comment by infogulch** [comment] 2021-04-05 21:44
Hi @sungam3r, were you able to identify the cause, or do you have any idea yet of the scope of the changes required to implement the fix?

**Comment by sungam3r** [comment] 2021-04-06 11:35
Sorry. Too much work yet. I keep this page open.

**Comment by sungam3r** [comment] 2021-04-09 20:28
Sorry, a lot of work. I will keep this page open.

**Comment by sungam3r** [comment] 2021-04-16 18:20
May be related to #553

**Comment by sungam3r** [comment] 2021-12-28 22:41
@infogulch  So... I returned back to check your tests. The problem is that you use invalid schema for your test - `BasicSchema<T>`:
```
 private static ISchema BasicSchema<T>()
        {
            string defs = @"
                type Query {
                    post(id: ID!): String
                }
            ";

            return Schema.For(defs, _ => _.Types.Include<T>());
        }
```
Obviously, there is no `Data` type. The policies check algorithm does not find the right type.

**Comment by sungam3r** [comment] 2022-02-04 10:53
Closed due to lack of feedback.

**Closed by sungam3r** 2022-02-04 10:53 UTC
Labels: enhancement, needs confirmation
